# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 888)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 888))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 888))
        MainWindow.setWindowTitle("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setSpacing(9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.button_open = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_open.setMinimumSize(QtCore.QSize(0, 30))
        self.button_open.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_open.setObjectName("button_open")
        self.verticalLayout_7.addWidget(self.button_open)
        self.button_pred = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_pred.setMinimumSize(QtCore.QSize(0, 30))
        self.button_pred.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_pred.setObjectName("button_pred")
        self.verticalLayout_7.addWidget(self.button_pred)
        self.button_gt = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_gt.setMinimumSize(QtCore.QSize(0, 30))
        self.button_gt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_gt.setObjectName("button_gt")
        self.verticalLayout_7.addWidget(self.button_gt)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem1)
        self.label_slice = QtWidgets.QLabel(self.horizontalWidget)
        self.label_slice.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_slice.setText("")
        self.label_slice.setObjectName("label_slice")
        self.verticalLayout_7.addWidget(self.label_slice)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.gridWidget = QtWidgets.QWidget(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.container_flair = QtWidgets.QWidget(self.gridWidget)
        self.container_flair.setStyleSheet("")
        self.container_flair.setObjectName("container_flair")
        self.layout_flair = QtWidgets.QVBoxLayout(self.container_flair)
        self.layout_flair.setContentsMargins(0, 0, 0, 0)
        self.layout_flair.setSpacing(0)
        self.layout_flair.setObjectName("layout_flair")
        self.label_2 = QtWidgets.QLabel(self.container_flair)
        self.label_2.setObjectName("label_2")
        self.layout_flair.addWidget(self.label_2)
        self.viewer_flair = Viewer(self.container_flair)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.viewer_flair.sizePolicy().hasHeightForWidth())
        self.viewer_flair.setSizePolicy(sizePolicy)
        self.viewer_flair.setMinimumSize(QtCore.QSize(384, 384))
        self.viewer_flair.setMouseTracking(True)
        self.viewer_flair.setStyleSheet("background-color: #a0a0a0;")
        self.viewer_flair.setText("")
        self.viewer_flair.setScaledContents(False)
        self.viewer_flair.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer_flair.setObjectName("viewer_flair")
        self.layout_flair.addWidget(self.viewer_flair)
        self.gridLayout.addWidget(self.container_flair, 1, 2, 1, 1)
        self.container_t2 = QtWidgets.QWidget(self.gridWidget)
        self.container_t2.setStyleSheet("")
        self.container_t2.setObjectName("container_t2")
        self.layout_t2 = QtWidgets.QVBoxLayout(self.container_t2)
        self.layout_t2.setContentsMargins(0, 0, 0, 0)
        self.layout_t2.setSpacing(0)
        self.layout_t2.setObjectName("layout_t2")
        self.label = QtWidgets.QLabel(self.container_t2)
        self.label.setObjectName("label")
        self.layout_t2.addWidget(self.label)
        self.viewer_t2 = Viewer(self.container_t2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.viewer_t2.sizePolicy().hasHeightForWidth())
        self.viewer_t2.setSizePolicy(sizePolicy)
        self.viewer_t2.setMinimumSize(QtCore.QSize(384, 384))
        self.viewer_t2.setMouseTracking(True)
        self.viewer_t2.setStyleSheet("background-color: #a0a0a0;")
        self.viewer_t2.setText("")
        self.viewer_t2.setScaledContents(False)
        self.viewer_t2.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer_t2.setObjectName("viewer_t2")
        self.layout_t2.addWidget(self.viewer_t2)
        self.gridLayout.addWidget(self.container_t2, 1, 1, 1, 1)
        self.container_t1 = QtWidgets.QWidget(self.gridWidget)
        self.container_t1.setStyleSheet("")
        self.container_t1.setObjectName("container_t1")
        self.layout_t1 = QtWidgets.QVBoxLayout(self.container_t1)
        self.layout_t1.setContentsMargins(0, 0, 0, 0)
        self.layout_t1.setSpacing(0)
        self.layout_t1.setObjectName("layout_t1")
        self.label_3 = QtWidgets.QLabel(self.container_t1)
        self.label_3.setObjectName("label_3")
        self.layout_t1.addWidget(self.label_3)
        self.viewer_t1 = Viewer(self.container_t1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.viewer_t1.sizePolicy().hasHeightForWidth())
        self.viewer_t1.setSizePolicy(sizePolicy)
        self.viewer_t1.setMinimumSize(QtCore.QSize(384, 384))
        self.viewer_t1.setMouseTracking(True)
        self.viewer_t1.setStyleSheet("background-color: #a0a0a0;")
        self.viewer_t1.setText("")
        self.viewer_t1.setScaledContents(False)
        self.viewer_t1.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer_t1.setObjectName("viewer_t1")
        self.layout_t1.addWidget(self.viewer_t1)
        self.gridLayout.addWidget(self.container_t1, 0, 1, 1, 1)
        self.container_t1ce = QtWidgets.QWidget(self.gridWidget)
        self.container_t1ce.setStyleSheet("")
        self.container_t1ce.setObjectName("container_t1ce")
        self.layout_t1ce = QtWidgets.QVBoxLayout(self.container_t1ce)
        self.layout_t1ce.setContentsMargins(0, 0, 0, 0)
        self.layout_t1ce.setSpacing(0)
        self.layout_t1ce.setObjectName("layout_t1ce")
        self.label_4 = QtWidgets.QLabel(self.container_t1ce)
        self.label_4.setObjectName("label_4")
        self.layout_t1ce.addWidget(self.label_4)
        self.viewer_t1ce = Viewer(self.container_t1ce)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.viewer_t1ce.sizePolicy().hasHeightForWidth())
        self.viewer_t1ce.setSizePolicy(sizePolicy)
        self.viewer_t1ce.setMinimumSize(QtCore.QSize(384, 384))
        self.viewer_t1ce.setMouseTracking(True)
        self.viewer_t1ce.setStyleSheet("background-color: #a0a0a0;")
        self.viewer_t1ce.setText("")
        self.viewer_t1ce.setScaledContents(False)
        self.viewer_t1ce.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer_t1ce.setObjectName("viewer_t1ce")
        self.layout_t1ce.addWidget(self.viewer_t1ce)
        self.gridLayout.addWidget(self.container_t1ce, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.gridWidget)
        self.slider = QtWidgets.QSlider(self.horizontalWidget)
        self.slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider.setMinimum(1)
        self.slider.setMaximum(128)
        self.slider.setProperty("value", 64)
        self.slider.setOrientation(QtCore.Qt.Vertical)
        self.slider.setInvertedAppearance(False)
        self.slider.setInvertedControls(False)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.verticalLayout.addWidget(self.horizontalWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.button_open.setText(_translate("MainWindow", "打开项目"))
        self.button_pred.setText(_translate("MainWindow", "显示/隐藏预测结果"))
        self.button_gt.setText(_translate("MainWindow", "显示/隐藏参考标准"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "FLAIR(T2 fluid attenuated inversion recovery)"))
        self.label.setText(_translate("MainWindow", "T2(T2-weighted)"))
        self.label_3.setText(_translate("MainWindow", "T1(native)"))
        self.label_4.setText(_translate("MainWindow", "T1Gd(post-contrast T1-weighted)"))
        self.action_open.setText(_translate("MainWindow", "打开项目"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))

from main import Viewer
